github에서 새로운 repository를 생성하고, readme 파일에 간단한 설명을 적었다. 이후 로컬에서 git init, add ,commit 을 실행하고, git push
명령어를 이용하여 로컬 레포지토리의 내용을 github 원격 레포지토리로 push 하려 했으나 다음과 같은 오류가 발생하였다.

error: failed to push some refs to '~~~'
hint : Updates were rejected because the remote contains work that you do not have locally.

원인:원격 저장소에서 새로운 repository를 생성하고, readme 파일을 만들었는데, 로컬저장소에 동기화가 되지 않은 상태라 로컬 레포지토리 내용이 push가 되지 않는것.

해결방안:원격저장소의 변경사항을 로컬저장소로 git pull origin master 시키고 그 뒤에 로컬에서 push를 하면 정상처리 될 것이다.
